OBJ = mscobj

SRCS_PLATFORM = \
	src/tdme/os/network/platform/fallback/KernelEventMechanism.cpp \
	src/tdme/engine/fileio/models/FBXReader.cpp \
	src/tdme/engine/fileio/models/ModelReaderFBX.cpp

INCLUDES = \
	/I "." \
	/I "src" \
	/I "ext" \
	/I "ext\src" \
	/I "ext\v-hacd\src\VHACD_Lib\inc" \
	/I "ext\reactphysics3d\src" \
	/I "ext\fbx\win64\include" \
	/I "ext\glfw3\include" \
	/I "ext\windows-msc\pthread\includes" \
	/I "ext\windows-msc\openal-soft\includes" \
	/I "ext\windows-msc\glew\include" \
	/I "ext\windows-msc\dirent\include" \
	/I "ext\windows-msc\vulkan-sdk\include" \
	/I "ext\rapidjson\include"

# For some reason this works only once LOL
# WINDOWS_SDK_DIR = %WindowsSdkDir%Lib\%WindowsSDKLibVersion%
WINDOWS_SDK_DIR = C:\Program Files (x86)\Windows Kits\10\Lib\10.0.19041.0

MAIN_LDFLAGS = \
	/LIBPATH libtdme-ext.lib \
	/LIBPATH libtdme.lib

LIBS_LDFLAGS = \
	/LIBPATH "$(WINDOWS_SDK_DIR)\um\x64\user32.lib" \
	/LIBPATH "$(WINDOWS_SDK_DIR)\um\x64\ws2_32.lib" \
	/LIBPATH "$(WINDOWS_SDK_DIR)\um\x64\dbghelp.lib" \
	/LIBPATH "ext\glfw3\win64\lib\glfw3dll.lib" \
	/LIBPATH "ext\windows-msc\pthread\libs\pthreadVC2.lib" \
	/LIBPATH "ext\windows-msc\openal-soft\libs\OpenAL32.lib" \
	/LIBPATH "ext\fbx\win64\lib\libfbxsdk.lib" \

FLAGS = /MT /MP /EHsc /O2 /std:c++20 /Zi /F 8388608 /D RAPIDJSON_HAS_STDSTRING /D GLFW_DLL
# /NODEFAULTLIB:msvcrt

LD_FLAGS =

SRC = src
TINYXML = tinyxml
ZLIB = zlib
LIBPNG = libpng
VORBIS = vorbis
OGG = ogg
VHACD = v-hacd
REACTPHYSICS3D = reactphysics3d

SRCS = \
	src/tdme/audio/Audio.cpp \
	src/tdme/audio/AudioBufferManager.cpp \
	src/tdme/audio/AudioStream.cpp \
	src/tdme/audio/PacketAudioStream.cpp \
	src/tdme/audio/VorbisAudioStream.cpp \
	src/tdme/audio/Sound.cpp \
	src/tdme/audio/decoder/AudioDecoderException.cpp \
	src/tdme/audio/decoder/VorbisDecoder.cpp \
	src/tdme/application/Application.cpp \
	src/tdme/application/InputEventHandler.cpp \
	src/tdme/engine/Camera.cpp \
	src/tdme/engine/DynamicColorTexture.cpp \
	src/tdme/engine/Engine.cpp \
	src/tdme/engine/EntityHierarchy.cpp \
	src/tdme/engine/EntityShaderParameters.cpp \
	src/tdme/engine/EnvironmentMapping.cpp \
	src/tdme/engine/FogParticleSystem.cpp \
	src/tdme/engine/FrameBuffer.cpp \
	src/tdme/engine/Frustum.cpp \
	src/tdme/engine/GeometryBuffer.cpp \
	src/tdme/engine/ImposterObject3D.cpp \
	src/tdme/engine/Light.cpp \
	src/tdme/engine/LinesObject3D.cpp \
	src/tdme/engine/LODObject3D.cpp \
	src/tdme/engine/LODObject3DImposter.cpp \
	src/tdme/engine/Object3D.cpp \
	src/tdme/engine/Object3DModel.cpp \
	src/tdme/engine/Object3DRenderGroup.cpp \
	src/tdme/engine/ObjectParticleSystem.cpp \
	src/tdme/engine/OctTreePartition.cpp \
	src/tdme/engine/ParticleSystemGroup.cpp \
	src/tdme/engine/PointsParticleSystem.cpp \
	src/tdme/engine/Rotation.cpp \
	src/tdme/engine/SceneConnector.cpp \
	src/tdme/engine/SimplePartition.cpp \
	src/tdme/engine/Timing.cpp \
	src/tdme/engine/Transformations.cpp \
	src/tdme/engine/Version.cpp \
	src/tdme/engine/fileio/models/DAEReader.cpp \
	src/tdme/engine/fileio/models/GLTFReader.cpp \
	src/tdme/engine/fileio/models/ModelFileIOException.cpp \
	src/tdme/engine/fileio/models/TMReader.cpp \
	src/tdme/engine/fileio/models/TMWriter.cpp \
	src/tdme/engine/fileio/models/WFObjWriter.cpp \
	src/tdme/engine/fileio/prototypes/PrototypeWriter.cpp \
	src/tdme/engine/fileio/prototypes/PrototypeReader.cpp \
	src/tdme/engine/fileio/scenes/SceneWriter.cpp \
	src/tdme/engine/fileio/scenes/SceneReader.cpp \
	src/tdme/engine/fileio/textures/PNGTextureWriter.cpp \
	src/tdme/engine/fileio/textures/Texture.cpp \
	src/tdme/engine/fileio/textures/TextureReader.cpp \
	src/tdme/engine/model/Animation.cpp \
	src/tdme/engine/model/AnimationSetup.cpp \
	src/tdme/engine/model/Face.cpp \
	src/tdme/engine/model/FacesEntity.cpp \
	src/tdme/engine/model/Node.cpp \
	src/tdme/engine/model/Joint.cpp \
	src/tdme/engine/model/JointWeight.cpp \
	src/tdme/engine/model/Material.cpp \
	src/tdme/engine/model/Model.cpp \
	src/tdme/engine/model/UpVector.cpp \
	src/tdme/engine/model/PBRMaterialProperties.cpp \
	src/tdme/engine/model/RotationOrder.cpp \
	src/tdme/engine/model/Skinning.cpp \
	src/tdme/engine/model/ShaderModel.cpp \
	src/tdme/engine/model/SpecularMaterialProperties.cpp \
	src/tdme/engine/model/TextureCoordinate.cpp \
	src/tdme/engine/physics/Body.cpp \
	src/tdme/engine/physics/World.cpp \
	src/tdme/engine/prototype/BaseProperties.cpp \
	src/tdme/engine/prototype/BaseProperty.cpp \
	src/tdme/engine/primitives/BoundingBox.cpp \
	src/tdme/engine/primitives/BoundingVolume.cpp \
	src/tdme/engine/primitives/Capsule.cpp \
	src/tdme/engine/primitives/ConvexMesh.cpp \
	src/tdme/engine/primitives/HeightMap.cpp \
	src/tdme/engine/primitives/LineSegment.cpp \
	src/tdme/engine/primitives/OrientedBoundingBox.cpp \
	src/tdme/engine/primitives/Sphere.cpp \
	src/tdme/engine/primitives/TerrainMesh.cpp \
	src/tdme/engine/primitives/Triangle.cpp \
	src/tdme/engine/prototype/Prototype.cpp \
	src/tdme/engine/prototype/PrototypeAudio.cpp \
	src/tdme/engine/prototype/PrototypeBoundingVolume.cpp \
	src/tdme/engine/prototype/PrototypeImposterLOD.cpp \
	src/tdme/engine/prototype/PrototypeLODLevel.cpp \
	src/tdme/engine/prototype/PrototypeParticleSystem.cpp \
	src/tdme/engine/prototype/PrototypeParticleSystem_BoundingBoxParticleEmitter.cpp \
	src/tdme/engine/prototype/PrototypeParticleSystem_CircleParticleEmitter.cpp \
	src/tdme/engine/prototype/PrototypeParticleSystem_CircleParticleEmitterPlaneVelocity.cpp \
	src/tdme/engine/prototype/PrototypeParticleSystem_Emitter.cpp \
	src/tdme/engine/prototype/PrototypeParticleSystem_FogParticleSystem.cpp \
	src/tdme/engine/prototype/PrototypeParticleSystem_ObjectParticleSystem.cpp \
	src/tdme/engine/prototype/PrototypeParticleSystem_PointParticleEmitter.cpp \
	src/tdme/engine/prototype/PrototypeParticleSystem_PointParticleSystem.cpp \
	src/tdme/engine/prototype/PrototypeParticleSystem_SphereParticleEmitter.cpp \
	src/tdme/engine/prototype/PrototypeParticleSystem_Type.cpp \
	src/tdme/engine/prototype/PrototypePhysics.cpp \
	src/tdme/engine/prototype/PrototypePhysics_BodyType.cpp \
	src/tdme/engine/prototype/Prototype_Type.cpp \
	src/tdme/engine/scene/Scene.cpp \
	src/tdme/engine/scene/SceneEntity.cpp \
	src/tdme/engine/scene/SceneLibrary.cpp \
	src/tdme/engine/scene/SceneLight.cpp \
	src/tdme/engine/scene/ScenePropertyPresets.cpp \
	src/tdme/engine/subsystems/earlyzrejection/EZRShader.cpp \
	src/tdme/engine/subsystems/earlyzrejection/EZRShaderBaseImplementation.cpp \
	src/tdme/engine/subsystems/earlyzrejection/EZRShaderDefaultImplementation.cpp \
	src/tdme/engine/subsystems/environmentmapping/EnvironmentMappingRenderer.cpp \
	src/tdme/engine/subsystems/framebuffer/DeferredLightingRenderShader.cpp \
	src/tdme/engine/subsystems/framebuffer/FrameBufferRenderShader.cpp \
	src/tdme/engine/subsystems/lighting/DeferredLightingShaderDefaultImplementation.cpp \
	src/tdme/engine/subsystems/lighting/DeferredLightingShaderFoliageImplementation.cpp \
	src/tdme/engine/subsystems/lighting/DeferredLightingShaderPBRDefaultImplementation.cpp \
	src/tdme/engine/subsystems/lighting/DeferredLightingShaderPBRFoliageImplementation.cpp \
	src/tdme/engine/subsystems/lighting/DeferredLightingShaderPBRTreeImplementation.cpp \
	src/tdme/engine/subsystems/lighting/DeferredLightingShaderSkyImplementation.cpp \
	src/tdme/engine/subsystems/lighting/DeferredLightingShaderTerrainImplementation.cpp \
	src/tdme/engine/subsystems/lighting/DeferredLightingShaderTreeImplementation.cpp \
	src/tdme/engine/subsystems/lighting/LightingShader.cpp \
	src/tdme/engine/subsystems/lighting/LightingShaderBaseImplementation.cpp \
	src/tdme/engine/subsystems/lighting/LightingShaderDefaultImplementation.cpp \
	src/tdme/engine/subsystems/lighting/LightingShaderFoliageImplementation.cpp \
	src/tdme/engine/subsystems/lighting/LightingShaderLightScatteringDefaultImplementation.cpp \
	src/tdme/engine/subsystems/lighting/LightingShaderLightScatteringFoliageImplementation.cpp \
	src/tdme/engine/subsystems/lighting/LightingShaderLightScatteringTreeImplementation.cpp \
	src/tdme/engine/subsystems/lighting/LightingShaderPBRBaseImplementation.cpp \
	src/tdme/engine/subsystems/lighting/LightingShaderPBRDefaultImplementation.cpp \
	src/tdme/engine/subsystems/lighting/LightingShaderPBRFoliageImplementation.cpp \
	src/tdme/engine/subsystems/lighting/LightingShaderPBRTreeImplementation.cpp \
	src/tdme/engine/subsystems/lighting/LightingShaderSkyImplementation.cpp \
	src/tdme/engine/subsystems/lighting/LightingShaderTerrainEditorImplementation.cpp \
	src/tdme/engine/subsystems/lighting/LightingShaderTerrainImplementation.cpp \
	src/tdme/engine/subsystems/lighting/LightingShaderTreeImplementation.cpp \
	src/tdme/engine/subsystems/lighting/LightingShaderWaterImplementation.cpp \
	src/tdme/engine/subsystems/lines/LinesShader.cpp \
	src/tdme/engine/subsystems/lines/LinesObject3DInternal.cpp \
	src/tdme/engine/subsystems/manager/MeshManager.cpp \
	src/tdme/engine/subsystems/manager/MeshManager_MeshManaged.cpp \
	src/tdme/engine/subsystems/manager/TextureManager.cpp \
	src/tdme/engine/subsystems/manager/TextureManager_TextureManaged.cpp \
	src/tdme/engine/subsystems/manager/VBOManager.cpp \
	src/tdme/engine/subsystems/manager/VBOManager_VBOManaged.cpp \
	src/tdme/engine/subsystems/rendering/BatchRendererPoints.cpp \
	src/tdme/engine/subsystems/rendering/BatchRendererTriangles.cpp \
	src/tdme/engine/subsystems/rendering/ModelUtilitiesInternal.cpp \
	src/tdme/engine/subsystems/rendering/Object3DAnimation.cpp \
	src/tdme/engine/subsystems/rendering/Object3DBase.cpp \
	src/tdme/engine/subsystems/rendering/Object3DBase_TransformedFacesIterator.cpp \
	src/tdme/engine/subsystems/rendering/Object3DNode.cpp \
	src/tdme/engine/subsystems/rendering/Object3DNodeMesh.cpp \
	src/tdme/engine/subsystems/rendering/Object3DNodeRenderer.cpp \
	src/tdme/engine/subsystems/rendering/Object3DInternal.cpp \
	src/tdme/engine/subsystems/rendering/Object3DModelInternal.cpp \
	src/tdme/engine/subsystems/rendering/EntityRenderer.cpp \
	src/tdme/engine/subsystems/rendering/EntityRenderer_TransparentRenderFacesGroupPool.cpp \
	src/tdme/engine/subsystems/rendering/ObjectBuffer.cpp \
	src/tdme/engine/subsystems/rendering/RenderTransparentRenderPointsPool.cpp \
	src/tdme/engine/subsystems/rendering/TransparentRenderFacesGroup.cpp \
	src/tdme/engine/subsystems/rendering/TransparentRenderFacesPool.cpp \
	src/tdme/engine/subsystems/rendering/TransparentRenderFacesPool_TransparentRenderFacesPool.cpp \
	src/tdme/engine/subsystems/rendering/TransparentRenderPointsPool.cpp \
	src/tdme/engine/subsystems/particlesystem/BoundingBoxParticleEmitter.cpp \
	src/tdme/engine/subsystems/particlesystem/CircleParticleEmitter.cpp \
	src/tdme/engine/subsystems/particlesystem/CircleParticleEmitterPlaneVelocity.cpp \
	src/tdme/engine/subsystems/particlesystem/FogParticleSystemInternal.cpp \
	src/tdme/engine/subsystems/particlesystem/ObjectParticleSystemInternal.cpp \
	src/tdme/engine/subsystems/particlesystem/ParticlesShader.cpp \
	src/tdme/engine/subsystems/particlesystem/PointParticleEmitter.cpp \
	src/tdme/engine/subsystems/particlesystem/PointsParticleSystemInternal.cpp \
	src/tdme/engine/subsystems/particlesystem/SphereParticleEmitter.cpp \
	src/tdme/engine/subsystems/renderer/Renderer.cpp \
	src/tdme/engine/subsystems/postprocessing/PostProcessing.cpp \
	src/tdme/engine/subsystems/postprocessing/PostProcessingProgram.cpp \
	src/tdme/engine/subsystems/postprocessing/PostProcessingShader.cpp \
	src/tdme/engine/subsystems/postprocessing/PostProcessingShaderBaseImplementation.cpp \
	src/tdme/engine/subsystems/postprocessing/PostProcessingShaderBlurImplementation.cpp \
	src/tdme/engine/subsystems/postprocessing/PostProcessingShaderDefaultImplementation.cpp \
	src/tdme/engine/subsystems/postprocessing/PostProcessingShaderDesaturationImplementation.cpp \
	src/tdme/engine/subsystems/postprocessing/PostProcessingShaderLightScatteringImplementation.cpp \
	src/tdme/engine/subsystems/postprocessing/PostProcessingShaderSSAOImplementation.cpp \
	src/tdme/engine/subsystems/postprocessing/PostProcessingShaderSSAOMapImplementation.cpp \
	src/tdme/engine/subsystems/postprocessing/PostProcessingShaderVignetteImplementation.cpp \
	src/tdme/engine/subsystems/shadowmapping/ShadowMap.cpp \
	src/tdme/engine/subsystems/shadowmapping/ShadowMapping.cpp \
	src/tdme/engine/subsystems/shadowmapping/ShadowMapCreationShader.cpp \
	src/tdme/engine/subsystems/shadowmapping/ShadowMapCreationShaderBaseImplementation.cpp \
	src/tdme/engine/subsystems/shadowmapping/ShadowMapCreationShaderDefaultImplementation.cpp \
	src/tdme/engine/subsystems/shadowmapping/ShadowMapCreationShaderFoliageImplementation.cpp \
	src/tdme/engine/subsystems/shadowmapping/ShadowMapCreationShaderTreeImplementation.cpp \
	src/tdme/engine/subsystems/shadowmapping/ShadowMapRenderShader.cpp \
	src/tdme/engine/subsystems/shadowmapping/ShadowMapRenderShaderBaseImplementation.cpp \
	src/tdme/engine/subsystems/shadowmapping/ShadowMapRenderShaderDefaultImplementation.cpp \
	src/tdme/engine/subsystems/shadowmapping/ShadowMapRenderShaderFoliageImplementation.cpp \
	src/tdme/engine/subsystems/shadowmapping/ShadowMapRenderShaderTreeImplementation.cpp \
	src/tdme/engine/subsystems/skinning/SkinningShader.cpp \
	src/tdme/engine/subsystems/texture2D/Texture2DRenderShader.cpp \
	src/tdme/gui/GUI.cpp \
	src/tdme/gui/GUIParser.cpp \
	src/tdme/gui/GUIParserException.cpp \
	src/tdme/gui/effects/GUIColorEffect.cpp \
	src/tdme/gui/effects/GUIEffect.cpp \
	src/tdme/gui/effects/GUIPositionEffect.cpp \
	src/tdme/gui/elements/GUIButton.cpp \
	src/tdme/gui/elements/GUIButtonController.cpp \
	src/tdme/gui/elements/GUICheckbox.cpp \
	src/tdme/gui/elements/GUICheckboxController.cpp \
	src/tdme/gui/elements/GUIContextMenu.cpp \
	src/tdme/gui/elements/GUIContextMenuController.cpp \
	src/tdme/gui/elements/GUIContextMenuItem.cpp \
	src/tdme/gui/elements/GUIContextMenuItemController.cpp \
	src/tdme/gui/elements/GUIDropDown.cpp \
	src/tdme/gui/elements/GUIDropDownController.cpp \
	src/tdme/gui/elements/GUIDropDownOption.cpp \
	src/tdme/gui/elements/GUIDropDownOptionController.cpp \
	src/tdme/gui/elements/GUIElement.cpp \
	src/tdme/gui/elements/GUIImageButton.cpp \
	src/tdme/gui/elements/GUIInput.cpp \
	src/tdme/gui/elements/GUIInputController.cpp \
	src/tdme/gui/elements/GUIKnob.cpp \
	src/tdme/gui/elements/GUIKnobController.cpp \
	src/tdme/gui/elements/GUIMenuHeader.cpp \
	src/tdme/gui/elements/GUIMenuHeaderController.cpp \
	src/tdme/gui/elements/GUIMenuHeaderItem.cpp \
	src/tdme/gui/elements/GUIMenuHeaderItemController.cpp \
	src/tdme/gui/elements/GUIMenuItem.cpp \
	src/tdme/gui/elements/GUIMenuItemController.cpp \
	src/tdme/gui/elements/GUIMenuSeparator.cpp \
	src/tdme/gui/elements/GUIProgressBar.cpp \
	src/tdme/gui/elements/GUIProgressBarController.cpp \
	src/tdme/gui/elements/GUIRadioButton.cpp \
	src/tdme/gui/elements/GUIRadioButtonController.cpp \
	src/tdme/gui/elements/GUISelectorH.cpp \
	src/tdme/gui/elements/GUISelectorHController.cpp \
	src/tdme/gui/elements/GUISelectorHOption.cpp \
	src/tdme/gui/elements/GUISelectorHOptionController.cpp \
	src/tdme/gui/elements/GUIScrollArea.cpp \
	src/tdme/gui/elements/GUIScrollAreaController.cpp \
	src/tdme/gui/elements/GUISelectBox.cpp \
	src/tdme/gui/elements/GUISelectBoxController.cpp \
	src/tdme/gui/elements/GUISelectBoxOption.cpp \
	src/tdme/gui/elements/GUISelectBoxOptionController.cpp \
	src/tdme/gui/elements/GUISelectBoxParentOption.cpp \
	src/tdme/gui/elements/GUISelectBoxParentOptionController.cpp \
	src/tdme/gui/elements/GUISliderH.cpp \
	src/tdme/gui/elements/GUISliderHController.cpp \
	src/tdme/gui/elements/GUISliderV.cpp \
	src/tdme/gui/elements/GUISliderVController.cpp \
	src/tdme/gui/elements/GUIStyledInput.cpp \
	src/tdme/gui/elements/GUIStyledInputController.cpp \
	src/tdme/gui/elements/GUITab.cpp \
	src/tdme/gui/elements/GUITabContent.cpp \
	src/tdme/gui/elements/GUITabContentController.cpp \
	src/tdme/gui/elements/GUITabController.cpp \
	src/tdme/gui/elements/GUITabs.cpp \
	src/tdme/gui/elements/GUITabsContent.cpp \
	src/tdme/gui/elements/GUITabsController.cpp \
	src/tdme/gui/elements/GUITabsHeader.cpp \
	src/tdme/gui/elements/GUITabsHeaderController.cpp \
	src/tdme/gui/nodes/GUIColor.cpp \
	src/tdme/gui/nodes/GUIElementController.cpp \
	src/tdme/gui/nodes/GUIElementIgnoreEventsController.cpp \
	src/tdme/gui/nodes/GUIElementNode.cpp \
	src/tdme/gui/nodes/GUIFrameBufferNode.cpp \
	src/tdme/gui/nodes/GUIGradientNode.cpp \
	src/tdme/gui/nodes/GUIHorizontalScrollbarInternalController.cpp \
	src/tdme/gui/nodes/GUIHorizontalScrollbarInternalNode.cpp \
	src/tdme/gui/nodes/GUIImageNode.cpp \
	src/tdme/gui/nodes/GUIInputInternalController.cpp \
	src/tdme/gui/nodes/GUIInputInternalNode.cpp \
	src/tdme/gui/nodes/GUILayerNode.cpp \
	src/tdme/gui/nodes/GUILayoutNode.cpp \
	src/tdme/gui/nodes/GUILayoutNode_Alignment.cpp \
	src/tdme/gui/nodes/GUINode.cpp \
	src/tdme/gui/nodes/GUINodeConditions.cpp \
	src/tdme/gui/nodes/GUINodeController.cpp \
	src/tdme/gui/nodes/GUINode_AlignmentHorizontal.cpp \
	src/tdme/gui/nodes/GUINode_AlignmentVertical.cpp \
	src/tdme/gui/nodes/GUINode_Flow.cpp \
	src/tdme/gui/nodes/GUINode_RequestedConstraints_RequestedConstraintsType.cpp \
	src/tdme/gui/nodes/GUIPanelNode.cpp \
	src/tdme/gui/nodes/GUIParentNode.cpp \
	src/tdme/gui/nodes/GUIParentNode_Overflow.cpp \
	src/tdme/gui/nodes/GUIScreenNode.cpp \
	src/tdme/gui/nodes/GUISpaceNode.cpp \
	src/tdme/gui/nodes/GUIStyledTextNode.cpp \
	src/tdme/gui/nodes/GUIStyledTextNodeController.cpp \
	src/tdme/gui/nodes/GUITableNode.cpp \
	src/tdme/gui/nodes/GUITableCellNode.cpp \
	src/tdme/gui/nodes/GUITableRowNode.cpp \
	src/tdme/gui/nodes/GUITextNode.cpp \
	src/tdme/gui/nodes/GUITextureBaseNode.cpp \
	src/tdme/gui/nodes/GUITextureNode.cpp \
	src/tdme/gui/nodes/GUIVerticalScrollbarInternalController.cpp \
	src/tdme/gui/nodes/GUIVerticalScrollbarInternalNode.cpp \
	src/tdme/gui/nodes/GUIVideoNode.cpp \
	src/tdme/gui/renderer/GUIFont.cpp \
	src/tdme/gui/renderer/GUIRenderer.cpp \
	src/tdme/gui/renderer/GUIShader.cpp \
	src/tdme/network/httpclient/HTTPClient.cpp \
	src/tdme/network/httpclient/HTTPClientException.cpp \
	src/tdme/network/httpclient/HTTPDownloadClient.cpp \
	src/tdme/network/udpclient/NetworkClientException.cpp \
	src/tdme/network/udpclient/UDPClient.cpp \
	src/tdme/network/udpclient/UDPClientMessage.cpp \
	src/tdme/network/udpserver/NetworkServerException.cpp \
	src/tdme/network/udpserver/ServerClient.cpp \
	src/tdme/network/udpserver/ServerClientRequestHandlerHubException.cpp \
	src/tdme/network/udpserver/ServerRequest.cpp \
	src/tdme/network/udpserver/ServerWorkerThread.cpp \
	src/tdme/network/udpserver/ServerWorkerThreadPool.cpp \
	src/tdme/network/udpserver/UDPServer.cpp \
	src/tdme/network/udpserver/UDPServerClient.cpp \
	src/tdme/network/udpserver/UDPServerIOThread.cpp \
	src/tdme/os/filesystem/ArchiveFileSystem.cpp \
	src/tdme/os/filesystem/FileSystem.cpp \
	src/tdme/os/filesystem/FileSystemException.cpp \
	src/tdme/os/filesystem/StandardFileSystem.cpp \
	src/tdme/os/network/Network.cpp \
	src/tdme/os/network/NetworkException.cpp \
	src/tdme/os/network/NetworkIOException.cpp \
	src/tdme/os/network/NetworkSocketClosedException.cpp \
	src/tdme/os/network/NetworkKEMException.cpp \
	src/tdme/os/network/NetworkSocket.cpp \
	src/tdme/os/network/NetworkSocketException.cpp \
	src/tdme/os/network/UDPSocket.cpp \
	src/tdme/os/network/TCPSocket.cpp \
	src/tdme/os/threading/Barrier.cpp \
	src/tdme/os/threading/Condition.cpp \
	src/tdme/os/threading/Mutex.cpp \
	src/tdme/os/threading/ReadWriteLock.cpp \
	src/tdme/os/threading/SpinLock.cpp \
	src/tdme/os/threading/Thread.cpp \
	src/tdme/tests/AngleTest.cpp \
	src/tdme/tests/AudioTest.cpp \
	src/tdme/tests/CrashTest.cpp \
	src/tdme/tests/EngineTest.cpp \
	src/tdme/tests/EntityHierarchyTest.cpp \
	src/tdme/tests/LODTest.cpp \
	src/tdme/tests/FlowMapTest.cpp \
	src/tdme/tests/FlowMapTest2.cpp \
	src/tdme/tests/FoliageTest.cpp \
	src/tdme/tests/MathOperatorTest.cpp \
	src/tdme/tests/MiniScriptTest.cpp \
	src/tdme/tests/PathFindingTest.cpp \
	src/tdme/tests/PivotTest.cpp \
	src/tdme/tests/PhysicsTest1.cpp \
	src/tdme/tests/PhysicsTest2.cpp \
	src/tdme/tests/PhysicsTest3.cpp \
	src/tdme/tests/PhysicsTest4.cpp \
	src/tdme/tests/RayTracingTest.cpp \
	src/tdme/tests/ThreadingTest_ConsumerThread.cpp \
	src/tdme/tests/ThreadingTest_ProducerThread.cpp \
	src/tdme/tests/ThreadingTest_TestThread.cpp \
	src/tdme/tests/TreeTest.cpp \
	src/tdme/tests/UDPServerTest_UDPServer.cpp \
	src/tdme/tests/UDPServerTest_UDPServerClient.cpp \
	src/tdme/tests/SkinningTest.cpp \
	src/tdme/tests/VideoTest.cpp \
	src/tdme/tests/WaterTest.cpp \
	src/tdme/tools/editor/TDMEEditor.cpp \
	src/tdme/tools/editor/controllers/AboutDialogScreenController.cpp \
	src/tdme/tools/editor/controllers/ColorPickerImageController.cpp \
	src/tdme/tools/editor/controllers/ColorPickerScreenController.cpp \
	src/tdme/tools/editor/controllers/ContextMenuScreenController.cpp \
	src/tdme/tools/editor/controllers/EditorScreenController.cpp \
	src/tdme/tools/editor/controllers/FileDialogScreenController.cpp \
	src/tdme/tools/editor/controllers/InfoDialogScreenController.cpp \
	src/tdme/tools/editor/controllers/ProgressBarScreenController.cpp \
	src/tdme/tools/editor/misc/CameraInputHandler.cpp \
	src/tdme/tools/editor/misc/CameraRotationInputHandler.cpp \
	src/tdme/tools/editor/misc/GenerateBillboardLOD.cpp \
	src/tdme/tools/editor/misc/GenerateConvexMeshes.cpp \
	src/tdme/tools/editor/misc/GenerateImposterLOD.cpp \
	src/tdme/tools/editor/misc/Gizmo.cpp \
	src/tdme/tools/editor/misc/PopUps.cpp \
	src/tdme/tools/editor/misc/TextFormatter.cpp \
	src/tdme/tools/editor/misc/Tools.cpp \
	src/tdme/tools/editor/tabcontrollers/EmptyEditorTabController.cpp \
	src/tdme/tools/editor/tabcontrollers/EnvMapEditorTabController.cpp \
	src/tdme/tools/editor/tabcontrollers/FontTabController.cpp \
	src/tdme/tools/editor/tabcontrollers/ModelEditorTabController.cpp \
	src/tdme/tools/editor/tabcontrollers/ParticleSystemEditorTabController.cpp \
	src/tdme/tools/editor/tabcontrollers/SceneEditorTabController.cpp \
	src/tdme/tools/editor/tabcontrollers/SoundTabController.cpp \
	src/tdme/tools/editor/tabcontrollers/TerrainEditorTabController.cpp \
	src/tdme/tools/editor/tabcontrollers/TextureTabController.cpp \
	src/tdme/tools/editor/tabcontrollers/TextEditorTabController.cpp \
	src/tdme/tools/editor/tabcontrollers/TriggerEditorTabController.cpp \
	src/tdme/tools/editor/tabcontrollers/UIEditorTabController.cpp \
	src/tdme/tools/editor/tabcontrollers/subcontrollers/BasePropertiesSubController.cpp \
	src/tdme/tools/editor/tabcontrollers/subcontrollers/PrototypeDisplaySubController.cpp \
	src/tdme/tools/editor/tabcontrollers/subcontrollers/PrototypePhysicsSubController.cpp \
	src/tdme/tools/editor/tabcontrollers/subcontrollers/PrototypePhysicsSubController_BoundingVolumeType.cpp \
	src/tdme/tools/editor/tabcontrollers/subcontrollers/PrototypeSoundsSubController.cpp \
	src/tdme/tools/editor/tabviews/EmptyEditorTabView.cpp \
	src/tdme/tools/editor/tabviews/EnvMapEditorTabView.cpp \
	src/tdme/tools/editor/tabviews/FontTabView.cpp \
	src/tdme/tools/editor/tabviews/ModelEditorTabView.cpp \
	src/tdme/tools/editor/tabviews/ParticleSystemEditorTabView.cpp \
	src/tdme/tools/editor/tabviews/SceneEditorTabView.cpp \
	src/tdme/tools/editor/tabviews/SoundTabView.cpp \
	src/tdme/tools/editor/tabviews/TerrainEditorTabView.cpp \
	src/tdme/tools/editor/tabviews/TextureTabView.cpp \
	src/tdme/tools/editor/tabviews/TextEditorTabView.cpp \
	src/tdme/tools/editor/tabviews/TriggerEditorTabView.cpp \
	src/tdme/tools/editor/tabviews/UIEditorTabView.cpp \
	src/tdme/tools/editor/tabviews/subviews/BasePropertiesSubView.cpp \
	src/tdme/tools/editor/tabviews/subviews/PrototypeDisplaySubView.cpp \
	src/tdme/tools/editor/tabviews/subviews/PrototypePhysicsSubView.cpp \
	src/tdme/tools/editor/tabviews/subviews/PrototypeSoundsSubView.cpp \
	src/tdme/tools/editor/views/EditorView.cpp \
	src/tdme/tools/installer/Installer.cpp \
	src/tdme/utilities/Base64.cpp \
	src/tdme/utilities/Console.cpp \
	src/tdme/utilities/ExceptionBase.cpp \
	src/tdme/utilities/Enum.cpp \
	src/tdme/utilities/Float.cpp \
	src/tdme/utilities/Hex.cpp \
	src/tdme/utilities/Integer.cpp \
	src/tdme/utilities/MiniScript.cpp \
	src/tdme/utilities/ModelTools.cpp \
	src/tdme/utilities/PathFinding.cpp \
	src/tdme/utilities/Primitives.cpp \
	src/tdme/utilities/Properties.cpp \
	src/tdme/utilities/Reference.cpp \
	src/tdme/utilities/RTTI.cpp \
	src/tdme/utilities/SHA256.cpp \
	src/tdme/utilities/StringTools.cpp \
	src/tdme/utilities/StringTokenizer.cpp \
	src/tdme/utilities/Terrain.cpp \
	src/tdme/video/decoder/MPEG1Decoder.cpp \
	src/tdme/video/decoder/VideoDecoderException.cpp \
	$(SRCS_PLATFORM)

EXT_SRCS = \

EXT_TINYXML_SRCS = \
	ext/tinyxml/tinystr.cpp \
	ext/tinyxml/tinyxml.cpp \
	ext/tinyxml/tinyxmlerror.cpp \
	ext/tinyxml/tinyxmlparser.cpp

EXT_ZLIB_SRCS = \
	ext/zlib/adler32.c \
	ext/zlib/crc32.c \
	ext/zlib/deflate.c \
	ext/zlib/infback.c \
	ext/zlib/inffast.c \
	ext/zlib/inflate.c \
	ext/zlib/inftrees.c \
	ext/zlib/trees.c \
	ext/zlib/zutil.c \
	ext/zlib/compress.c \
	ext/zlib/uncompr.c \
	ext/zlib/gzclose.c \
	ext/zlib/gzlib.c \
	ext/zlib/gzread.c \
	ext/zlib/gzwrite.c

EXT_LIBPNG_SRCS = \
	ext/libpng/pngrio.c \
	ext/libpng/pngwio.c \
	ext/libpng/pngmem.c \
	ext/libpng/pngwtran.c \
	ext/libpng/pngtrans.c \
	ext/libpng/pngerror.c \
	ext/libpng/pngpread.c \
	ext/libpng/pngget.c \
	ext/libpng/pngset.c \
	ext/libpng/pngwrite.c \
	ext/libpng/pngwutil.c \
	ext/libpng/pngread.c \
	ext/libpng/pngrutil.c \
	ext/libpng/png.c \
	ext/libpng/pngrtran.c

EXT_VORBIS_SRCS = \
	ext/vorbis/analysis.c \
	ext/vorbis/barkmel.c \
	ext/vorbis/bitrate.c \
	ext/vorbis/block.c \
	ext/vorbis/codebook.c \
	ext/vorbis/envelope.c \
	ext/vorbis/floor0.c \
	ext/vorbis/floor1.c \
	ext/vorbis/info.c \
	ext/vorbis/lookup.c \
	ext/vorbis/lpc.c \
	ext/vorbis/lsp.c \
	ext/vorbis/mapping0.c \
	ext/vorbis/mdct.c \
	ext/vorbis/misc.c \
	ext/vorbis/psy.c \
	ext/vorbis/registry.c \
	ext/vorbis/res0.c \
	ext/vorbis/sharedbook.c \
	ext/vorbis/smallft.c \
	ext/vorbis/synthesis.c \
	ext/vorbis/vorbisenc.c \
	ext/vorbis/vorbisfile.c \
	ext/vorbis/window.c

EXT_OGG_SRCS = \
	ext/ogg/bitwise.c \
	ext/ogg/framing.c

EXT_SHA256_SRCS = \
    ext/sha256/sha256.cpp

EXT_VHACD_SRCS = \
	ext/v-hacd/src/VHACD_Lib/src/FloatMath.cpp \
	ext/v-hacd/src/VHACD_Lib/src/VHACD-ASYNC.cpp \
	ext/v-hacd/src/VHACD_Lib/src/VHACD.cpp \
	ext/v-hacd/src/VHACD_Lib/src/btAlignedAllocator.cpp \
	ext/v-hacd/src/VHACD_Lib/src/btConvexHullComputer.cpp \
	ext/v-hacd/src/VHACD_Lib/src/vhacdICHull.cpp \
	ext/v-hacd/src/VHACD_Lib/src/vhacdManifoldMesh.cpp \
	ext/v-hacd/src/VHACD_Lib/src/vhacdMesh.cpp \
	ext/v-hacd/src/VHACD_Lib/src/vhacdRaycastMesh.cpp \
	ext/v-hacd/src/VHACD_Lib/src/vhacdVolume.cpp

EXT_REACTPHYSICS3D_SRCS = \
	ext/reactphysics3d/src/body/Body.cpp \
	ext/reactphysics3d/src/body/CollisionBody.cpp \
	ext/reactphysics3d/src/body/RigidBody.cpp \
	ext/reactphysics3d/src/collision/ContactManifoldInfo.cpp \
	ext/reactphysics3d/src/collision/broadphase/BroadPhaseAlgorithm.cpp \
	ext/reactphysics3d/src/collision/broadphase/DynamicAABBTree.cpp \
	ext/reactphysics3d/src/collision/narrowphase/DefaultCollisionDispatch.cpp \
	ext/reactphysics3d/src/collision/narrowphase/GJK/VoronoiSimplex.cpp \
	ext/reactphysics3d/src/collision/narrowphase/GJK/GJKAlgorithm.cpp \
	ext/reactphysics3d/src/collision/narrowphase/SAT/SATAlgorithm.cpp \
	ext/reactphysics3d/src/collision/narrowphase/CapsuleVsCapsuleAlgorithm.cpp \
	ext/reactphysics3d/src/collision/narrowphase/SphereVsCapsuleAlgorithm.cpp \
	ext/reactphysics3d/src/collision/narrowphase/SphereVsSphereAlgorithm.cpp \
	ext/reactphysics3d/src/collision/narrowphase/SphereVsConvexPolyhedronAlgorithm.cpp \
	ext/reactphysics3d/src/collision/narrowphase/CapsuleVsConvexPolyhedronAlgorithm.cpp \
	ext/reactphysics3d/src/collision/narrowphase/ConvexPolyhedronVsConvexPolyhedronAlgorithm.cpp \
	ext/reactphysics3d/src/collision/shapes/AABB.cpp \
	ext/reactphysics3d/src/collision/shapes/ConvexShape.cpp \
	ext/reactphysics3d/src/collision/shapes/ConvexPolyhedronShape.cpp \
	ext/reactphysics3d/src/collision/shapes/ConcaveShape.cpp \
	ext/reactphysics3d/src/collision/shapes/BoxShape.cpp \
	ext/reactphysics3d/src/collision/shapes/CapsuleShape.cpp \
	ext/reactphysics3d/src/collision/shapes/CollisionShape.cpp \
	ext/reactphysics3d/src/collision/shapes/ConvexMeshShape.cpp \
	ext/reactphysics3d/src/collision/shapes/SphereShape.cpp \
	ext/reactphysics3d/src/collision/shapes/TriangleShape.cpp \
	ext/reactphysics3d/src/collision/shapes/ConcaveMeshShape.cpp \
	ext/reactphysics3d/src/collision/shapes/HeightFieldShape.cpp \
	ext/reactphysics3d/src/collision/RaycastInfo.cpp \
	ext/reactphysics3d/src/collision/ProxyShape.cpp \
	ext/reactphysics3d/src/collision/TriangleVertexArray.cpp \
	ext/reactphysics3d/src/collision/PolygonVertexArray.cpp \
	ext/reactphysics3d/src/collision/TriangleMesh.cpp \
	ext/reactphysics3d/src/collision/PolyhedronMesh.cpp \
	ext/reactphysics3d/src/collision/HalfEdgeStructure.cpp \
	ext/reactphysics3d/src/collision/CollisionDetection.cpp \
	ext/reactphysics3d/src/collision/NarrowPhaseInfo.cpp \
	ext/reactphysics3d/src/collision/ContactManifold.cpp \
	ext/reactphysics3d/src/collision/ContactManifoldSet.cpp \
	ext/reactphysics3d/src/collision/MiddlePhaseTriangleCallback.cpp \
	ext/reactphysics3d/src/constraint/BallAndSocketJoint.cpp \
	ext/reactphysics3d/src/constraint/ContactPoint.cpp \
	ext/reactphysics3d/src/constraint/FixedJoint.cpp \
	ext/reactphysics3d/src/constraint/HingeJoint.cpp \
	ext/reactphysics3d/src/constraint/Joint.cpp \
	ext/reactphysics3d/src/constraint/SliderJoint.cpp \
	ext/reactphysics3d/src/engine/CollisionWorld.cpp \
	ext/reactphysics3d/src/engine/ConstraintSolver.cpp \
	ext/reactphysics3d/src/engine/ContactSolver.cpp \
	ext/reactphysics3d/src/engine/DynamicsWorld.cpp \
	ext/reactphysics3d/src/engine/Island.cpp \
	ext/reactphysics3d/src/engine/Material.cpp \
	ext/reactphysics3d/src/engine/OverlappingPair.cpp \
	ext/reactphysics3d/src/engine/Timer.cpp \
	ext/reactphysics3d/src/collision/CollisionCallback.cpp \
	ext/reactphysics3d/src/mathematics/mathematics_functions.cpp \
	ext/reactphysics3d/src/mathematics/Matrix2x2.cpp \
	ext/reactphysics3d/src/mathematics/Matrix3x3.cpp \
	ext/reactphysics3d/src/mathematics/Quaternion.cpp \
	ext/reactphysics3d/src/mathematics/Transform.cpp \
	ext/reactphysics3d/src/mathematics/Vector2.cpp \
	ext/reactphysics3d/src/mathematics/Vector3.cpp \
	ext/reactphysics3d/src/memory/MemoryManager.cpp \
	ext/reactphysics3d/src/memory/DefaultSingleFrameAllocator.cpp \
	ext/reactphysics3d/src/memory/DefaultPoolAllocator.cpp

EXT_SRCS = \
	$(EXT_TINYXML_SRCS) \
	$(EXT_ZLIB_SRCS) \
	$(EXT_LIBPNG_SRCS) \
	$(EXT_VORBIS_SRCS) \
	$(EXT_OGG_SRCS) \
	$(EXT_SHA256_SRCS) \
	$(EXT_VHACD_SRCS) \
	$(EXT_REACTPHYSICS3D_SRCS)

OPENGL3CORE_RENDERER_LIB_SRCS = \
	src/tdme/engine/subsystems/renderer/EngineGL3Renderer.cpp \
	src/tdme/engine/subsystems/renderer/GL3Renderer.cpp

OPENGL2_RENDERER_LIB_SRCS = \
	src/tdme/engine/subsystems/renderer/EngineGL2Renderer.cpp \
	src/tdme/engine/subsystems/renderer/GL2Renderer.cpp

VULKAN_RENDERER_LIB_SRCS = \
	ext/vulkan/spirv/GlslangToSpv.cpp \
	ext/vulkan/spirv/InReadableOrder.cpp \
	ext/vulkan/spirv/Logger.cpp \
	ext/vulkan/spirv/SPVRemapper.cpp \
	ext/vulkan/spirv/SpvBuilder.cpp \
	ext/vulkan/spirv/SpvPostProcess.cpp \
	ext/vulkan/spirv/SpvTools.cpp \
	ext/vulkan/spirv/disassemble.cpp \
	ext/vulkan/spirv/doc.cpp \
	ext/vulkan/glslang/MachineIndependent/glslang_tab.cpp \
	ext/vulkan/glslang/MachineIndependent/attribute.cpp \
	ext/vulkan/glslang/MachineIndependent/Constant.cpp \
	ext/vulkan/glslang/MachineIndependent/iomapper.cpp \
	ext/vulkan/glslang/MachineIndependent/InfoSink.cpp \
	ext/vulkan/glslang/MachineIndependent/Initialize.cpp \
	ext/vulkan/glslang/MachineIndependent/IntermTraverse.cpp \
	ext/vulkan/glslang/MachineIndependent/Intermediate.cpp \
	ext/vulkan/glslang/MachineIndependent/ParseContextBase.cpp \
	ext/vulkan/glslang/MachineIndependent/ParseHelper.cpp \
	ext/vulkan/glslang/MachineIndependent/PoolAlloc.cpp \
	ext/vulkan/glslang/MachineIndependent/RemoveTree.cpp \
	ext/vulkan/glslang/MachineIndependent/Scan.cpp \
	ext/vulkan/glslang/MachineIndependent/ShaderLang.cpp \
	ext/vulkan/glslang/MachineIndependent/SymbolTable.cpp \
	ext/vulkan/glslang/MachineIndependent/Versions.cpp \
	ext/vulkan/glslang/MachineIndependent/intermOut.cpp \
	ext/vulkan/glslang/MachineIndependent/limits.cpp \
	ext/vulkan/glslang/MachineIndependent/linkValidate.cpp \
	ext/vulkan/glslang/MachineIndependent/parseConst.cpp \
	ext/vulkan/glslang/MachineIndependent/reflection.cpp \
	ext/vulkan/glslang/MachineIndependent/preprocessor/Pp.cpp \
	ext/vulkan/glslang/MachineIndependent/preprocessor/PpAtom.cpp \
	ext/vulkan/glslang/MachineIndependent/preprocessor/PpContext.cpp \
	ext/vulkan/glslang/MachineIndependent/preprocessor/PpScanner.cpp \
	ext/vulkan/glslang/MachineIndependent/preprocessor/PpTokens.cpp \
	ext/vulkan/glslang/MachineIndependent/propagateNoContraction.cpp \
	ext/vulkan/glslang/GenericCodeGen/CodeGen.cpp \
	ext/vulkan/glslang/GenericCodeGen/Link.cpp \
	ext/vulkan/OGLCompilersDLL/InitializeDll.cpp \
	ext/vulkan/vma/src/VmaUsage.cpp \
	ext/vulkan/glslang/OSDependent/Windows/ossource.cpp \
	src/tdme/engine/subsystems/renderer/EngineVKRenderer.cpp \
	src/tdme/engine/subsystems/renderer/VKGL3CoreShaderProgram.cpp \
	src/tdme/engine/subsystems/renderer/VKRenderer.cpp \
	ext/windows-msc/uint128_t/uint128_t.cpp

all: \
	ext-init ext-compile ext-link1 ext-link2 ext-clean \
	init compile link1 link2 clean \
	opengl3core-init opengl3core-compile opengl3core-link1 opengl3core-link2 opengl3core-clean \
	opengl2-init opengl2-compile opengl2-link1 opengl2-link2 opengl2-clean \
	vulkan-init vulkan-compile vulkan-link1 vulkan-link2 vulkan-clean \
	init-mains \
	AngleTest \
	AudioTest \
	ContainerTest \
	CrashTest \
	EngineTest \
	EntityHierarchyTest \
	HTTPClientTest \
	HTTPDownloadClientTest \
	LODTest \
	FlowMapTest \
	FlowMapTest2 \
	FoliageTest \
	MathOperatorTest \
	MiniScriptTest \
	PathFindingTest \
	PhysicsTest1 PhysicsTest2 PhysicsTest3 PhysicsTest4 \
	RayTracingTest \
	SkinningTest \
	ThreadingTest \
	TreeTest \
	UDPClientTest \
	UDPServerTest \
	VideoTest \
	WaterTest \
	archive \
	collectguitags \
	converttotm \
	copyanimationsetups \
	createinstaller \
	imageprocessor \
	recreatevkcache \
	generatelicenses \
	importtmodel \
	fixdoxygen \
	msclib2dll \
	makefilegenerator \
	miniscripttranspiler \
	optimizemodel \
	parseh++ \
	scenefixmodelszup2yup \
	sortincludes \
	TDMEEditor \
	InstallerApp \
	clean-mains

ext-init:
	mkdir $(OBJ)

ext-compile: $(EXT_SRCS)
	cl /Fo$(OBJ)/ /c $(FLAGS) $(INCLUDES) $**

ext-link1: $(OBJ)/*.obj
	lib $(LD_FLAGS) /OUT:libtdme-ext.lib $**
	dumpbin /LINKERMEMBER libtdme-ext.lib > libtdme-ext.def.dumpbin.linkermember
	.\ext\windows-msc\tools\msclib2dll.exe libtdme-ext.def.dumpbin.linkermember
	del libtdme-ext.lib

ext-link2: $(OBJ)/*.obj
	echo LIBRARY libtdme-ext.dll > libtdme-ext.def
	type libtdme-ext.def.dumpbin.linkermember.def >> libtdme-ext.def
	link $(LD_FLAGS) /DLL /DEF:libtdme-ext.def /IGNORE:4197 /IGNORE:4102 $** $(LIBS_LDFLAGS) /OUT:libtdme-ext.dll
	del libtdme-ext.def.dumpbin.linkermember
	del libtdme-ext.def.dumpbin.linkermember.def

ext-clean:$(OBJ)/*.obj
	del /S /Q $(OBJ) >nul 2>&1
	rmdir $(OBJ)

init:
	mkdir $(OBJ) 

init-mains:
	mkdir $(OBJ)

compile: $(SRCS)
	cl /D TDME2_DLL_EXPORT /Fo$(OBJ)/ /c $(FLAGS) $(INCLUDES) $**

link1: $(OBJ)/*.obj
	lib $(LD_FLAGS) /OUT:libtdme.lib $**
	dumpbin /LINKERMEMBER libtdme.lib > libtdme.def.dumpbin.linkermember
	.\ext\windows-msc\tools\msclib2dll.exe libtdme.def.dumpbin.linkermember
	del libtdme.lib

link2: $(OBJ)/*.obj
	echo LIBRARY libtdme.dll > libtdme.def
	type libtdme.def.dumpbin.linkermember.def >> libtdme.def
	link $(LD_FLAGS) /DLL /DEF:libtdme.def /IGNORE:4197 /IGNORE:4102 $** $(LIBS_LDFLAGS) /LIBPATH libtdme-ext.lib /OUT:libtdme.dll
	del libtdme.def.dumpbin.linkermember
	del libtdme.def.dumpbin.linkermember.def

clean: 
	del /S /Q $(OBJ) >nul 2>&1
	rmdir $(OBJ)

opengl3core-init:
	mkdir $(OBJ) 

opengl3core-mains:
	mkdir $(OBJ)

opengl3core-compile: $(OPENGL3CORE_RENDERER_LIB_SRCS)
	cl /D TDME2_DLL_IMPORT /Fo$(OBJ)/ /c $(FLAGS) $(INCLUDES) $**

opengl3core-link1: $(OBJ)/*.obj
	lib $(LD_FLAGS) /OUT:libopengl3corerenderer.lib $**
	dumpbin /LINKERMEMBER libopengl3corerenderer.lib > libopengl3corerenderer.def.dumpbin.linkermember
	.\ext\windows-msc\tools\msclib2dll.exe libopengl3corerenderer.def.dumpbin.linkermember
	del libopengl3corerenderer.lib

opengl3core-link2: $(OBJ)/*.obj
	echo LIBRARY libopengl3corerenderer.dll > libopengl3corerenderer.def
	type libopengl3corerenderer.def.dumpbin.linkermember.def >> libopengl3corerenderer.def
	link $(LD_FLAGS) /DLL /DEF:libopengl3corerenderer.def /IGNORE:4197 /IGNORE:4102 $** $(LIBS_LDFLAGS) /LIBPATH libtdme.lib /LIBPATH "C:\Program Files (x86)\Windows Kits\10\Lib\10.0.19041.0\um\x64\opengl32.lib" /LIBPATH "ext\windows-msc\glew\libs\glew32.lib" /OUT:libopengl3corerenderer.dll
	del libopengl3corerenderer.def.dumpbin.linkermember
	del libopengl3corerenderer.def.dumpbin.linkermember.def

opengl3core-clean:
	del /S /Q $(OBJ) >nul 2>&1
	rmdir $(OBJ)

opengl2-init:
	mkdir $(OBJ)

opengl2-mains:
	mkdir $(OBJ)

opengl2-compile: $(OPENGL2_RENDERER_LIB_SRCS)
	cl /D TDME2_DLL_IMPORT /Fo$(OBJ)/ /c $(FLAGS) $(INCLUDES) $**

opengl2-link1: $(OBJ)/*.obj
	lib $(LD_FLAGS) /OUT:libopengl2renderer.lib $**
	dumpbin /LINKERMEMBER libopengl2renderer.lib > libopengl2renderer.def.dumpbin.linkermember
	.\ext\windows-msc\tools\msclib2dll.exe libopengl2renderer.def.dumpbin.linkermember
	del libopengl2renderer.lib

opengl2-link2: $(OBJ)/*.obj
	echo LIBRARY libopengl2renderer.dll > libopengl2renderer.def
	type libopengl2renderer.def.dumpbin.linkermember.def >> libopengl2renderer.def
	link $(LD_FLAGS) /DLL /DEF:libopengl2renderer.def /IGNORE:4197 /IGNORE:4197 /IGNORE:4102 $** $(LIBS_LDFLAGS) /LIBPATH libtdme.lib /LIBPATH "C:\Program Files (x86)\Windows Kits\10\Lib\10.0.19041.0\um\x64\opengl32.lib" /LIBPATH "ext\windows-msc\glew\libs\glew32.lib" /OUT:libopengl2renderer.dll
	del libopengl2renderer.def.dumpbin.linkermember
	del libopengl2renderer.def.dumpbin.linkermember.def

vulkan-clean:
	del /S /Q $(OBJ) >nul 2>&1
	rmdir $(OBJ)

vulkan-init:
	mkdir $(OBJ)

vulkan-mains:
	mkdir $(OBJ)

vulkan-compile: $(VULKAN_RENDERER_LIB_SRCS)
	cl /D TDME2_DLL_IMPORT /Fo$(OBJ)/ /c $(FLAGS) $(INCLUDES) $**

vulkan-link1: $(OBJ)/*.obj
	lib $(LD_FLAGS) /OUT:libvulkanrenderer.lib $**
	dumpbin /LINKERMEMBER libvulkanrenderer.lib > libvulkanrenderer.def.dumpbin.linkermember
	.\ext\windows-msc\tools\msclib2dll.exe libvulkanrenderer.def.dumpbin.linkermember
	del libvulkanrenderer.lib

vulkan-link2: $(OBJ)/*.obj
	echo LIBRARY libvulkanrenderer.dll > libvulkanrenderer.def
	echo DESCRIPTION libvulkanrenderer >> libvulkanrenderer.def
	type libvulkanrenderer.def.dumpbin.linkermember.def >> libvulkanrenderer.def
	link $(LD_FLAGS) /DLL /DEF:libvulkanrenderer.def /IGNORE:4197 /IGNORE:4102 $** $(LIBS_LDFLAGS) /LIBPATH libtdme.lib /LIBPATH "ext\vulkan\runtime\msc64\vulkan-1.lib" /OUT:libvulkanrenderer.dll
	del libvulkanrenderer.def.dumpbin.linkermember
	del libvulkanrenderer.def.dumpbin.linkermember.def

opengl2-clean:
	del /S /Q $(OBJ) >nul 2>&1
	rmdir $(OBJ)

clean-mains: 
	del /S /Q $(OBJ) >nul 2>&1
	rmdir $(OBJ)

AngleTest:
	cl /FeAngleTest /Fo$(OBJ)/ $(FLAGS) $(INCLUDES) src/tdme/tests/AngleTest-main.cpp /link $(LD_FLAGS) $(MAIN_LDFLAGS)
	
AudioTest:
	cl /FeAudioTest /Fo$(OBJ)/ $(FLAGS) $(INCLUDES) src/tdme/tests/AudioTest-main.cpp /link $(LD_FLAGS) $(MAIN_LDFLAGS)

ContainerTest:
	cl /FeContainerTest /Fo$(OBJ)/ $(FLAGS) $(INCLUDES) src/tdme/tests/ContainerTest-main.cpp /link $(LD_FLAGS) $(MAIN_LDFLAGS)

CrashTest:
	cl /FeCrashTest /Fo$(OBJ)/ $(FLAGS) $(INCLUDES) src/tdme/tests/CrashTest-main.cpp /link $(LD_FLAGS) $(MAIN_LDFLAGS)

EngineTest:
	cl /FeEngineTest /Fo$(OBJ)/ $(FLAGS) $(INCLUDES) src/tdme/tests/EngineTest-main.cpp /link $(LD_FLAGS) $(MAIN_LDFLAGS)

EntityHierarchyTest:
	cl /FeEntityHierarchyTest /Fo$(OBJ)/ $(FLAGS) $(INCLUDES) src/tdme/tests/EntityHierarchyTest-main.cpp /link $(LD_FLAGS) $(MAIN_LDFLAGS)

HTTPClientTest:
	cl /FeHTMLClientTest /Fo$(OBJ)/ $(FLAGS) $(INCLUDES) src/tdme/tests/HTTPClientTest-main.cpp /link $(LD_FLAGS) $(MAIN_LDFLAGS)

HTTPDownloadClientTest:
    cl /FeHTMLDownloadClientTest /Fo$(OBJ)/ $(FLAGS) $(INCLUDES) src/tdme/tests/HTTPDownloadClientTest-main.cpp /link $(LD_FLAGS) $(MAIN_LDFLAGS)

LODTest:
	cl /FeLODTest /Fo$(OBJ)/ $(FLAGS) $(INCLUDES) src/tdme/tests/LODTest-main.cpp /link $(LD_FLAGS) $(MAIN_LDFLAGS)

FlowMapTest:
	cl /FeFlowMapTest /Fo$(OBJ)/ $(FLAGS) $(INCLUDES) src/tdme/tests/FlowMapTest-main.cpp /link $(LD_FLAGS) $(MAIN_LDFLAGS)

FlowMapTest2:
	cl /FeFlowMapTest2 /Fo$(OBJ)/ $(FLAGS) $(INCLUDES) src/tdme/tests/FlowMapTest2-main.cpp /link $(LD_FLAGS) $(MAIN_LDFLAGS)

FoliageTest:
	cl /FeFoliageTest /Fo$(OBJ)/ $(FLAGS) $(INCLUDES) src/tdme/tests/FoliageTest-main.cpp /link $(LD_FLAGS) $(MAIN_LDFLAGS)

MathOperatorTest:
	cl /FeMathOperatorTest /Fo$(OBJ)/ $(FLAGS) $(INCLUDES) src/tdme/tests/MathOperatorTest-main.cpp /link $(LD_FLAGS) $(MAIN_LDFLAGS)

MiniScriptTest:
	cl /FeMiniScriptTest /Fo$(OBJ)/ $(FLAGS) $(INCLUDES) src/tdme/tests/MiniScriptTest-main.cpp /link $(LD_FLAGS) $(MAIN_LDFLAGS)

PathFindingTest:
	cl /FePathFindingTest /Fo$(OBJ)/ $(FLAGS) $(INCLUDES) src/tdme/tests/PathFindingTest-main.cpp /link $(LD_FLAGS) $(MAIN_LDFLAGS)

PhysicsTest1:
	cl /FePhysicsTest1 /Fo$(OBJ)/ $(FLAGS) $(INCLUDES) src/tdme/tests/PhysicsTest1-main.cpp /link $(LD_FLAGS) $(MAIN_LDFLAGS)

PhysicsTest2:
	cl /FePhysicsTest2 /Fo$(OBJ)/ $(FLAGS) $(INCLUDES) src/tdme/tests/PhysicsTest2-main.cpp /link $(LD_FLAGS) $(MAIN_LDFLAGS)

PhysicsTest3:
	cl /FePhysicsTest3 /Fo$(OBJ)/ $(FLAGS) $(INCLUDES) src/tdme/tests/PhysicsTest3-main.cpp /link $(LD_FLAGS) $(MAIN_LDFLAGS)

PhysicsTest4:
	cl /FePhysicsTest4 /Fo$(OBJ)/ $(FLAGS) $(INCLUDES) src/tdme/tests/PhysicsTest4-main.cpp /link $(LD_FLAGS) $(MAIN_LDFLAGS)

RayTracingTest:
	cl /FeRayTracingTest /Fo$(OBJ)/ $(FLAGS) $(INCLUDES) src/tdme/tests/RayTracingTest-main.cpp /link $(LD_FLAGS) $(MAIN_LDFLAGS)

SkinningTest:
	cl /FeSkinningTest /Fo$(OBJ)/ $(FLAGS) $(INCLUDES) src/tdme/tests/SkinningTest-main.cpp /link $(LD_FLAGS) $(MAIN_LDFLAGS)

ThreadingTest:
	cl /FeThreadingTest /Fo$(OBJ)/ $(FLAGS) $(INCLUDES) src/tdme/tests/ThreadingTest-main.cpp /link $(LD_FLAGS) $(MAIN_LDFLAGS)

TreeTest:
    cl /FeTreeTest /Fo$(OBJ)/ $(FLAGS) $(INCLUDES) src/tdme/tests/TreeTest-main.cpp /link $(LD_FLAGS) $(MAIN_LDFLAGS)

UDPClientTest:
	cl /FeUDPClientTest /Fo$(OBJ)/ $(FLAGS) $(INCLUDES) src/tdme/tests/UDPClientTest-main.cpp /link $(LD_FLAGS) $(MAIN_LDFLAGS)

UDPServerTest:
	cl /FeUDPServerTest /Fo$(OBJ)/ $(FLAGS) $(INCLUDES) src/tdme/tests/UDPServerTest-main.cpp /link $(LD_FLAGS) $(MAIN_LDFLAGS)

VideoTest:
	cl /FeVideoTest /Fo$(OBJ)/ $(FLAGS) $(INCLUDES) src/tdme/tests/VideoTest-main.cpp /link $(LD_FLAGS) $(MAIN_LDFLAGS)

WaterTest:
	cl /FeWaterTest $(FLAGS) /Fo$(OBJ)/ $(INCLUDES) src/tdme/tests/WaterTest-main.cpp /link $(LD_FLAGS) $(MAIN_LDFLAGS)

archive:
    cl /Fearchive $(FLAGS) /Fo$(OBJ)/ $(INCLUDES) src/tdme/tools/cli/archive-main.cpp /link $(LD_FLAGS) $(MAIN_LDFLAGS)

collectguitags:
	cl /Fecollectguitags $(FLAGS) /Fo$(OBJ)/ $(INCLUDES) src/tdme/tools/cli/collectguitags-main.cpp /link $(LD_FLAGS) $(MAIN_LDFLAGS)

converttotm:
	cl /Feconverttotm $(FLAGS) /Fo$(OBJ)/ $(INCLUDES) src/tdme/tools/cli/converttotm-main.cpp /link $(LD_FLAGS) $(MAIN_LDFLAGS)

copyanimationsetups:
	cl /Fecopyanimationsetups /Fo$(OBJ)/ $(FLAGS) $(INCLUDES) src/tdme/tools/cli/copyanimationsetups-main.cpp /link $(LD_FLAGS) $(MAIN_LDFLAGS)

createinstaller:
    cl /Fecreateinstaller $(FLAGS) /Fo$(OBJ)/ $(INCLUDES) src/tdme/tools/cli/createinstaller-main.cpp /link $(LD_FLAGS) $(MAIN_LDFLAGS)

imageprocessor:
    cl /Feimageprocessor $(FLAGS) /Fo$(OBJ)/ $(INCLUDES) src/tdme/tools/cli/imageprocessor-main.cpp /link $(LD_FLAGS) $(MAIN_LDFLAGS)

recreatevkcache:
    cl /Ferecreatevkcache $(FLAGS) /Fo$(OBJ)/ $(INCLUDES) src/tdme/tools/cli/recreatevkcache-main.cpp /link $(LD_FLAGS) $(MAIN_LDFLAGS)

generatelicenses:
	cl /Fegeneratelicenses /Fo$(OBJ)/ $(FLAGS) $(INCLUDES) src/tdme/tools/cli/generatelicenses-main.cpp /link $(LD_FLAGS) $(MAIN_LDFLAGS)

importtmodel:
	cl /Feimporttmodel /Fo$(OBJ)/ $(FLAGS) $(INCLUDES) src/tdme/tools/cli/importtmodel-main.cpp /link $(LD_FLAGS) $(MAIN_LDFLAGS)

fixdoxygen:
    cl /Fefixdoxygen /Fo$(OBJ)/ $(FLAGS) $(INCLUDES) src/tdme/tools/cli/fixdoxygen-main.cpp /link $(LD_FLAGS) $(MAIN_LDFLAGS)

msclib2dll:
    cl /Femsclib2dll /Fo$(OBJ)/ $(FLAGS) $(INCLUDES) src/tdme/tools/cli/msclib2dll-main.cpp /link $(LD_FLAGS) $(MAIN_LDFLAGS)

makefilegenerator:
	cl /Femakefilegenerator $(FLAGS) /Fo$(OBJ)/ $(INCLUDES) src/tdme/tools/cli/makefilegenerator-main.cpp /link $(LD_FLAGS) $(MAIN_LDFLAGS)

miniscripttranspiler:
	cl /Feminiscripttranspiler $(FLAGS) /Fo$(OBJ)/ $(INCLUDES) src/tdme/tools/cli/miniscripttranspiler-main.cpp /link $(LD_FLAGS) $(MAIN_LDFLAGS)

optimizemodel:
	cl /Feoptimizemodel $(FLAGS) /Fo$(OBJ)/ $(INCLUDES) src/tdme/tools/cli/optimizemodel-main.cpp /link $(LD_FLAGS) $(MAIN_LDFLAGS)

parseh++:
	cl /Feparseh++ $(FLAGS) /Fo$(OBJ)/ $(INCLUDES) src/tdme/tools/cli/parseh++-main.cpp /link $(LD_FLAGS) $(MAIN_LDFLAGS)

scenefixmodelszup2yup:
	cl /Fescenefixmodelszup2yup /Fo$(OBJ)/ $(FLAGS) $(INCLUDES) src/tdme/tools/cli/scenefixmodelszup2yup-main.cpp /link $(LD_FLAGS) $(MAIN_LDFLAGS)

sortincludes:
    cl /Fesortincludes /Fo$(OBJ)/ $(FLAGS) $(INCLUDES) src/tdme/tools/cli/sortincludes-main.cpp /link $(LD_FLAGS) $(MAIN_LDFLAGS)

TDMEEditor:
	cl /D TDME2_DLL_IMPORT /FeTDMEEditor /Fo$(OBJ)/ $(FLAGS) $(INCLUDES) src/tdme/tools/editor/TDMEEditor-main.cpp /link $(LD_FLAGS) $(MAIN_LDFLAGS)

InstallerApp:
	cl /FeInstaller /Fo$(OBJ)/ $(FLAGS) $(INCLUDES) src/tdme/tools/installer/Installer-main.cpp /link $(LD_FLAGS) $(MAIN_LDFLAGS)
