name: CI Ubuntu - Vulkan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: install required packages
        run: sudo apt update && sudo apt-get install libglew-dev libopenal-dev libglfw3-dev libvulkan-dev
      - uses: actions/checkout@v2
      - name: make mains VULKAN=YES
        run: make mains VULKAN=YES
